/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
select
country,
count(customer_key) as total_customer
from customers
group by country
order by total_customer desc;

-- Find the total product by gender
select 
gender,
count(customer_key) as total_customer
from customers
group by gender;

-- find the total product by category
select 
category,
count(product_name) as total_product
from products
group by category;

-- What is the AVERAGE price of each category
select 
category,
avg(cost) as avg_price
from products
group by category;

-- what is the total revenue generated for each country
SELECT
    p.category,
    SUM(s.sales_amount) AS total_revenue
FROM sales s
LEFT JOIN products p
    ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- What is the total revenue generated by each customer?
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(s.sales_amount) AS total_revenue
FROM sales s
LEFT JOIN customers c
    ON c.customer_key = s.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(s.quantity) AS total_sold_items
FROM sales s
LEFT JOIN customers c
    ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;